### ISSUE TITLE
Crash at launch

### ISSUE THREAD

**Issue by limburgher** [tux4kids/tuxmath#25]
Fedora 36.

#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at pthread_kill.c:44
        tid = <optimized out>
        ret = 0
        pd = <optimized out>

                    old_mask = {__val = {8374, 140737488344096, 93825003245216, 140737348354371, 93825003245296, 140737352645129, 8374, 0, 8374, 140737317446165, 4294955776, 93825003245296, 93825003241592, 93825003241600, 8589923424, 140737488344784}}
        ret = <optimized out>
#1  0x00007ffff7a6dcb3 in __pthread_kill_internal (signo=6, threadid=<optimized out>) at pthread_kill.c:78
#2  0x00007ffff7a1d9c6 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
        ret = <optimized out>
#3  0x00007ffff7a077f4 in __GI_abort () at abort.c:79
        save_stage = 1

                  act = {__sigaction_handler = {sa_handler = 0x20da46464952, sa_sigaction = 0x20da46464952}, sa_mask = {__val = {8, 0, 0, 69263977830, 20, 0, 0, 35967691153764, 44, 0, 0, 137438953480, 140737348350595, 137438953472, 93825003312128, 255}}, sa_flags = 99, sa_restorer = 0x7fffffffd660}

                    sigs = {__val = {32, 4627307879634829312, 4602678819172646912, 4629559679448514560, 4602678819172646912, 3121243357844279552, 140737329735872, 140737488344032, 93824993878864, 140737328909808, 140737329735872, 3121243357813145601, 140737329975296, 0, 140737488344032, 140737328902225}}
#4  0x00007ffff7a61d9e in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7ffff7b99925 "%s\n") at ../sysdeps/posix/libc_fatal.c:155
--Type <RET> for more, q to quit, c to continue without paging--c
        ap = {{gp_offset = 24, fp_offset = 0, overflow_arg_area = 0x7fffffffd590, reg_save_area = 0x7fffffffd520}}
        fd = <optimized out>
        list = <optimized out>
        nlist = <optimized out>
        cp = <optimized out>
#5  0x00007ffff7a7795c in malloc_printerr (str=str@entry=0x7ffff7b9c420 "free(): double free detected in tcache 2") at malloc.c:5664
#6  0x00007ffff7a79cec in _int_free (av=0x7ffff7bd7c80 <main_arena>, p=0x55555577b3e0, have_lock=0) at malloc.c:4473
        tmp = <optimized out>
        cnt = <optimized out>
        e = 0x55555577b3f0
        tc_idx = 28
        size = 480
        fb = <optimized out>
        nextchunk = <optimized out>
        nextsize = <optimized out>
        nextinuse = <optimized out>
        prevsize = <optimized out>
        bck = <optimized out>
        fwd = <optimized out>
        __PRETTY_FUNCTION__ = "_int_free"
#7  0x00007ffff7a7c143 in __GI___libc_free (mem=mem@entry=0x55555577b3f0) at malloc.c:3391
        ar_ptr = <optimized out>
        p = 0x55555577b3e0
        err = 2
#8  0x00007ffff7a580e7 in _IO_deallocate_file (fp=0x55555577b3f0) at /usr/src/debug/glibc-2.35-14.fc36.x86_64/libio/libioP.h:862
        status = -1
#9  _IO_new_fclose (fp=0x55555577b3f0) at iofclose.c:74
        status = -1
#10 0x00007ffff5d1d5d9 in stdio_close (context=0x555555fd21c0) at /usr/src/debug/SDL2-2.0.22-3.fc36.x86_64/src/file/SDL_rwops.c:658
        status = 0
#11 0x00007ffff7e98cd7 in RWops20to12_close (rwops12=0x555555fcbc00) at /usr/src/debug/sdl12-compat-0.0.1~git.20211125.4e4527a-4.fc36.x86_64/src/SDL12_compat.c:6833
        rc = 0
#12 0x00007ffff7e2003e in Mix_LoadWAV_RW (src=0x555555fcbc00, freesrc=freesrc@entry=1) at /usr/src/debug/SDL_mixer-1.2.12-24.fc36.x86_64/mixer.c:565
        magic = <optimized out>
        chunk = <optimized out>
        wavespec = {freq = 22050, format = 32784, channels = 1 '\001', silence = 0 '\000', samples = 4096, padding = 0, size = 0, callback = 0x0, userdata = 0x0}
        loaded = <optimized out>
        wavecvt = {needed = 1, src_format = 32784, dst_format = 32784, rate_incr = 1, buf = 0x5555560033c0 "", len = 8364, len_cvt = 16728, len_mult = 4, len_ratio = 2, filters = {0x7ffff5d00fe0 <SDL_Convert_S16_to_F32_SSE2>, 0x7ffff5cfa7f0 <SDL_ConvertMonoToStereo>, 0x7ffff5d01560 <SDL_Convert_F32_to_S16_SSE2>, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, filter_index = 3}
        samplesize = <optimized out>
#13 0x000055555555bd63 in load_sound_data () at /usr/src/debug/tuxmath-2.0.3-12.fc37.x86_64/src/fileops_media.c:271
        i = 4
#14 load_data_files () at /usr/src/debug/tuxmath-2.0.3-12.fc37.x86_64/src/setup.c:750
#15 setup (argv=<optimized out>, argc=<optimized out>) at /usr/src/debug/tuxmath-2.0.3-12.fc37.x86_64/src/setup.c:139
#16 main (argc=<optimized out>, argv=<optimized out>) at /usr/src/debug/tuxmath-2.0.3-12.fc37.x86_64/src/tuxmath.c:40

**Comment by StevenH928** [comment]
This issue is still extant.
